"$schema" = "../schemas/schema.json"

[default]
description = "Runtime permissions for camera, microphone and media on Android."
permissions = ["allow-check-permissions", "allow-request-permissions"]
